// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yntbkgrkgicddwmhqimy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludGJrZ3JrZ2ljZGR3bWhxaW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzEyOTIsImV4cCI6MjA2ODc0NzI5Mn0.FA2Q-Js_igGoXqd5Ajt2oolxt_WnuI-gghuPlY5rH-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});