// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amntnscgdmxemsjotqdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbnRuc2NnZG14ZW1zam90cWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjYzNTcsImV4cCI6MjA1NzA0MjM1N30.XZmGGcDWWQiGFYSsusaxeQlnYxTkRn5BvdD0o5R5C_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);